substitutions:
  name: deye
  deye_uart_id: sg03lp1_uart
  deye_uart_rx: GPIO13
  deye_uart_tx: GPIO14
  deye_modbus_id: sg03lp1_modbus
  deye_modbus_controller_id: sg03lp1_modbus_controller
  sdm230_modbus_id: sdm230_modbus
  sdm230_uart_id: sdm230_uart
  sdm230_uart_rx: GPIO21
  sdm230_uart_tx: GPIO22
  sdm230_mqtt_topic: solar/sdm230_emulator/data

esphome:
  name: ${name}

esp32:
  board: esp32dev
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  #power_save_mode: none

  ap:
    ssid: "${name} Fallback AP"
    password: !secret wifi_fallback_password

captive_portal:

logger:
  level: INFO

ota:
  platform: esphome
  password: !secret ota_password

web_server:
  port: 80

mqtt:
  broker: !secret mqtt_broker

uart:
  - id: ${deye_uart_id}
    rx_pin: ${deye_uart_rx}
    tx_pin: ${deye_uart_tx}
    baud_rate: 9600
    stop_bits: 1
  - id: ${sdm230_uart_id}
    rx_pin: ${sdm230_uart_rx}
    tx_pin: ${sdm230_uart_tx}
    baud_rate: 9600
    stop_bits: 1

modbus:
  - id: ${deye_modbus_id}
    uart_id: ${deye_uart_id}
  - id: ${sdm230_modbus_id}
    uart_id: ${sdm230_uart_id}
    role: server

modbus_controller: !include_dir_merge_list modbus_controller/

sensor: !include_dir_merge_list sensor/
text_sensor: !include_dir_merge_list text_sensor/
