
- platform: modbus_controller
  modbus_controller_id: ${deye_modbus_controller_id}
  name: "Deye SUN Warning1"
  id:  sun5k_Warning1
  register_type: holding
  address: 101
  accuracy_decimals: 0
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: ${deye_modbus_controller_id}
  name: "Deye SUN Warning2"
  id:  sun5k_Warning2
  register_type: holding
  address: 102
  accuracy_decimals: 0
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: ${deye_modbus_controller_id}
  name: "Deye SUN Fault1"
  id:  sun5k_Fault1
  register_type: holding
  address: 103
  accuracy_decimals: 0
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: ${deye_modbus_controller_id}
  name: "Deye SUN Fault2"
  id:  sun5k_Fault2
  register_type: holding
  address: 104
  accuracy_decimals: 0
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: ${deye_modbus_controller_id}
  name: "Deye SUN Fault3"
  id:  sun5k_Fault3
  register_type: holding
  address: 105
  accuracy_decimals: 0
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: ${deye_modbus_controller_id}
  name: "Deye SUN Fault4"
  id:  sun5k_Fault4
  register_type: holding
  address: 106
  accuracy_decimals: 0
  value_type: U_WORD

################################### PV
################################### Leistungsdaten PV1
- platform: modbus_controller
  modbus_controller_id: ${deye_modbus_controller_id}
  name: "Deye SUN AC Power"  # aktuelle AC Output Leistung
  id: sun5k_AC_Power
  register_type: holding
  address: 175
  state_class: "measurement"
  unit_of_measurement: "W"
  value_type: S_WORD

- platform: modbus_controller
  modbus_controller_id: ${deye_modbus_controller_id}
  name: "Deye SUN PV1 Power"  # aktuelle Leistung PV1
  id: sun5k_PV1_Power
  register_type: holding
  address: 186
  state_class: "measurement"
  unit_of_measurement: "W"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: ${deye_modbus_controller_id}
  name: "Deye SUN PV2 Power"  # aktuelle Leistung PV2
  id: sun5k_PV2_Power
  register_type: holding
  address: 187
  state_class: "measurement"
  unit_of_measurement: "W"
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: ${deye_modbus_controller_id}
  name: "Deye SUN Today PV Production" # leistung PV HEUTE in watt
  id: sun5k_daily_production
  register_type: holding
  address: 108
  unit_of_measurement: "kWh"
  state_class: "measurement"
  accuracy_decimals: 1
  filters:
    - multiply: 0.1
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: ${deye_modbus_controller_id}
  name: "Deye SUN PV1 Voltage" # aktuelle volt PV1
  id: sun5k_PV1_Voltage
  register_type: holding
  address: 109
  unit_of_measurement: "V"
  state_class: "measurement"
  accuracy_decimals: 1
  filters:
    - multiply: 0.1
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: ${deye_modbus_controller_id}
  name: "Deye SUN PV1 Current" # aktuelle A PV1
  id: sun5k_PV1_Current
  register_type: holding
  address: 110
  unit_of_measurement: "A"
  state_class: "measurement"
  accuracy_decimals: 1
  filters:
    - multiply: 0.1
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: ${deye_modbus_controller_id}
  name: "Deye SUN PV2 Voltage" # aktuelle volt PV2
  id: sun5k_PV2_Voltage
  register_type: holding
  address: 111
  unit_of_measurement: "V"
  state_class: "measurement"
  accuracy_decimals: 1
  filters:
    - multiply: 0.1
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: ${deye_modbus_controller_id}
  name: "Deye SUN PV2 Current" # aktuelle A PV2
  id: sun5k_PV2_Current
  register_type: holding
  address: 112
  unit_of_measurement: "A"
  state_class: "measurement"
  accuracy_decimals: 1
  filters:
    - multiply: 0.1
  value_type: U_WORD

- platform: modbus_controller
  modbus_controller_id: ${deye_modbus_controller_id}
  name: "Deye SUN Total PV Production"
  id: sun5k_Total_PV_Production
  register_type: holding
  address: 96
  unit_of_measurement: "kWh"
  state_class: "measurement"
  accuracy_decimals: 1
  filters:
    - multiply: 0.1
  value_type: U_DWORD_R

- platform: modbus_controller
  modbus_controller_id: ${deye_modbus_controller_id}
  name: "Deye SUN Radiator Temperature"
  id: sun5k_Radiator_Temperature
  register_type: holding
  address: 90
  unit_of_measurement: "℃"
  state_class: "measurement"
  accuracy_decimals: 1
  filters:
    - multiply: 0.1
    - offset: -100
  value_type: U_WORD

######################Ende PV Sensoren###########################################

################################ Batterie aktuelle Werte
- platform: modbus_controller          # 183 Battery Spannung
  modbus_controller_id: ${deye_modbus_controller_id}
  name: "Deye SUN Battery-Temperature"
  id: sun5k_Battery_Temperature
  register_type: holding
  address: 182
  unit_of_measurement: "℃"
  accuracy_decimals: 1
  filters:
    - multiply: 0.1
    - offset: -100
  device_class: voltage
  state_class: measurement
  value_type: U_WORD

- platform: modbus_controller          # 183 Battery Spannung
  modbus_controller_id: ${deye_modbus_controller_id}
  name: "Deye SUN Battery-Voltage"
  id: sun5k_Battery_Voltage
  register_type: holding
  address: 183
  unit_of_measurement: "V"
  accuracy_decimals: 2
  filters:
    - multiply: 0.01
  device_class: voltage
  state_class: measurement
  value_type: U_WORD

- platform: modbus_controller          # 184 Battery SOC
  modbus_controller_id:  ${deye_modbus_controller_id}
  name: "Deye SUN Battery-SoC"  #Batterie SoC
  id: sun5k_Battery_SoC
  register_type: holding
  address: 184
  unit_of_measurement: "%"
  #accuracy_decimals: 0
  device_class: battery
  state_class: measurement
  value_type: U_WORD

- platform: modbus_controller          # 190 Battery Output Current watt
  modbus_controller_id: ${deye_modbus_controller_id}
  name: "Deye SUN Battery-Power"
  id: sun5k_Battery_Power
  register_type: holding
  address: 190
  unit_of_measurement: "W"
  accuracy_decimals: 1
  device_class: power
  state_class: measurement
  value_type: S_WORD

- platform: modbus_controller          # 191 Battery Output Current Ampere
  modbus_controller_id: ${deye_modbus_controller_id}
  name: "Deye SUN Battery-Current"
  id: sun5k_Battery_Current
  register_type: holding
  address: 191
  unit_of_measurement: "A"
  accuracy_decimals: 2
  filters:
    - multiply: 0.01
  device_class: current
  state_class: measurement
  value_type: S_WORD
