
- platform: mqtt_subscribe
  name: "voltage"
  id: sdm230_voltage
  topic: sdm230_emulator/voltage
- platform: mqtt_subscribe
  name: "current"
  id: sdm230_current
  topic: sdm230_emulator/current
- platform: mqtt_subscribe
  name: "power"
  id: sdm230_power
  topic: sdm230_emulator/power
- platform: mqtt_subscribe
  name: "voltamps"
  id: sdm230_voltamps
  topic: sdm230_emulator/voltamps
- platform: mqtt_subscribe
  name: "reactivePower"
  id: sdm230_reactivePower
  topic: sdm230_emulator/reactivePower
- platform: mqtt_subscribe
  name: "powerFactor"
  id: sdm230_powerFactor
  topic: sdm230_emulator/powerFactor
- platform: mqtt_subscribe
  name: "phaseAngle"
  id: sdm230_phaseAngle
  topic: sdm230_emulator/phaseAngle
- platform: mqtt_subscribe
  name: "frequency"
  id: sdm230_frequency
  topic: sdm230_emulator/frequency
- platform: mqtt_subscribe
  name: "totalImportKWh"
  id: sdm230_totalImportKWh
  topic: sdm230_emulator/totalImportKWh
- platform: mqtt_subscribe
  name: "totalExportKWh"
  id: sdm230_totalExportKWh
  topic: sdm230_emulator/totalExportKWh
- platform: mqtt_subscribe
  name: "totalImportKVArh"
  id: sdm230_totalImportKVArh
  topic: sdm230_emulator/totalImportKVArh
- platform: mqtt_subscribe
  name: "totalExportKVArh"
  id: sdm230_totalExportKVArh
  topic: sdm230_emulator/totalExportKVArh